name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [ 11, 16 ]
        os: [ubuntu, windows ]
    steps:
      - name: Check out repo
        uses: actions/checkout@v2.3.2
      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Gradle
        uses: actions/cache@v2.1.5
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Run Gradle's test task
        run: ./gradlew --no-daemon --parallel --continue --build-cache --stacktrace test

  testDone:
    name: testOk
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: testOk
        run: echo 'all tests passed'
