name: test

on:
  push:
    branches:
      - main
    paths:
      - '**.java'
      - 'build.gradle'
      - 'build.gradle.kts'
      - 'gradle/wrapper/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.java'
      - 'build.gradle'
      - 'gradle/wrapper/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'
      - name: Run Gradle's test task
        run: ./gradlew --no-daemon --parallel --continue --build-cache --stacktrace test
  auto-merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: auto-merge
        if: |
          github.actor == 'dependabot[bot]' &&
          github.event_name == 'pull_request'
        run: |
          gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          # this secret needs to be in the settings.secrets.dependabot
          GITHUB_TOKEN: ${{secrets.GH_ACTION_TOKEN}}
